### ISSUE TITLE
Renamed psc-ide to psc-ide-client

### ISSUE THREAD

**Issue by kritzcreek** [FrigoEU/psc-ide-vim#1]
In order to be more consistent I renamed the psc-ide exectuable into psc-ide-client. This will take effect with the purescript-0.8.1 release.

**Comment by FrigoEU** [comment]
I pushed my latest updates under tag 0.1.0 for compiler version < 0.8.1. Next version, 0.2.0, assumes compiler version >= 0.8.1 and uses "psc-ide-client" instead of "psc-ide". Also added this to the readme.
