### ISSUE TITLE
Papply/PSCIDEapplySuggestion misses a newline when inserting missing top-level type declaration

### ISSUE THREAD

**Issue by andreasthoelke** [FrigoEU/psc-ide-vim#123]
`Papply`/`PSCIDEapplySuggestion` does not work as expected for me:

```purescript
-- Running :Papply on this line
test = "ab"

-- produces this output:
test :: Stingtest = "ab"

-- while this would be expected:
test :: Sting
test = "ab"
```
If I comment out this line https://github.com/FrigoEU/psc-ide-vim/blob/23bf302de91181d409fb988ce372ab703b119bc5/ftplugin/purescript_pscide.vim#L778
in `PSCIDEapplySuggestionPrime`

I get
```purescript
test :: Sting
 test = "ab"
```
(Note the false indentation of the second line)

The replacement insertion in `PSCIDEapplySuggestionPrime` is a bit involved, so not sure how to fix this.

**Comment by coot** [comment]
Could you please try if the fix works for you, especially if does not break other suggestions.
