### ISSUE TITLE
Error: failed to split case for: x

### ISSUE THREAD

**Issue by VictorTaelin** [FrigoEU/psc-ide-vim#13]
On this file:

```
module Main where

import Prelude
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Console (CONSOLE, log, print)

data Foo = Foo | Bar

foo :: Foo -> Int -> String
foo x _ = ?foo

main :: forall e. Eff (console :: CONSOLE | e) Unit
main = do
    log "Hello sailor!"
```

By calling `:PSCIDEaddClause` with cursor above the `x` variable on the `foo` declaration, I get the error:

```
Error: failed to split case for: x
```

Why?

**Comment by kritzcreek** [comment]
@MaiaVictor `addClause` is meant to be used on a type declaration. Try to use `caseSplit` instead.

**Comment by kritzcreek** [comment]
Did the casesplit command work for you? Can we close this?

**Comment by FrigoEU** [comment]
I tested both commands again, they do seem to work for me. I'm closing this since I'm assuming you just wanted to use caseSplit, but if you still think there's a bug feel free to reopen.
