### ISSUE TITLE
:Prebuild fails with unhelpful error

### ISSUE THREAD

**Issue by maackle** [FrigoEU/psc-ide-vim#130]
Sorry that this issue is so unhelpful, but I dug as far as I could and got no more information than this...

Simply firing up vim and running `:Prebuild` while editing a .purs file gives me this in `:messages`

```
purs ide: loaded 496 modules and 545 source files.
purs ide: failed to rebuild
purs: 1 error
```

Obviously I don't expect help with this but if anybody else is seeing this / has seen this perhaps we'll get somewhere...

**Comment by kritzcreek** [comment]
@maackle Step 1 would be to run `purs ide server --log-level=debug` in a separate terminal and use the VIM plugin against that. You'll need to remember to run the `load` command for attempting the rebuild! (Usually the plugin does that for you on startup)

**Comment by maackle** [comment]
Thanks for the tip, but I didn't get to try that because now I can't reproduce the problem! Hopefully it stays this way.
