### ISSUE TITLE
How about adding some new maintainers?

### ISSUE THREAD

**Issue by alextes** [FrigoEU/psc-ide-vim#148]
This project seems largely unmaintained, yet used by quite a few still. How about adding some new maintainers?

If you're interested in maintaining this project, please put your name down below. I'd be happy to step up myself and do some minimal maintaining if nobody else will but only as a last resort.

I've emailed the maintainer and asked him to check out this issue.

**Comment by FrigoEU** [comment]
Consider yourself invited!

**Comment by alextes** [comment]
Thanks FrigoEU!

For others reading this, I'll use my new powers to merge the odd, clearly well-tested PR, but _that's it!_. If you'd like this repo to move forward further and you feel comfortable enough with this codebase, please consider stepping up yourself!

I'll leave this issue open for that exact purpose.

**Comment by paluh** [comment]
Hi,

Could you please add me to the maintainers of this project? 

I'm a long standing user of _psc-ide-vim_ and I have three PRs waiting for merges (the most urgent is the last one as _psc-ide-vim_ is not working at all when you try it with _purs-0.14.1_) so I think I'm quite familiar already with the project internals.

**Comment by alextes** [comment]
@paluh I'm not using PureScript myself anymore. Adding maintainers it not something I can do 😥 .

I'll take a look at your PRs, if nothing more happens perhaps it's time to fork!

**Comment by paluh** [comment]
@alextes thanks for the info and merges!

@FrigoEU, could you please add me to the maintainers of this project?

**Comment by alextes** [comment]
@paluh it'd be nice to continue this repo but I wouldn't hesitate to merge if no reply comes. fwiw last time I got Simon over here by sending him an email.
