### ISSUE TITLE
"No matching autocommands" message

### ISSUE THREAD

**Issue by oblitum** [FrigoEU/psc-ide-vim#17]
Starting vim from a proper project directory and `:set ft=purescript` will give the "No matching autocommands" message.

**Comment by FrigoEU** [comment]
Can't seem to reproduce this. What version of vim/neovim are you using?

**Comment by natefaubion** [comment]
FWIW, I get this too (7.4)

**Comment by oblitum** [comment]
Vim version 7.4.2116.

**Comment by FrigoEU** [comment]
Fixed in 0.6.0 (just released)! Also added goToDefinition.
