### ISSUE TITLE
PSCIDEpursuit gives no results

### ISSUE THREAD

**Issue by oblitum** [FrigoEU/psc-ide-vim#18]
Currently I'm only getting "PSC-IDE: No results found on Pursuit" for anything my cursor is over.

**Comment by oblitum** [comment]
With log level 3:

```
callPscIde: start: Executing command: {'params': {'query': 'random', 'type': 'completion'}, 'command': 'pursuit'}
callPscIde: Raw response: {"result":[],"resultType":"success"}
callPscIde: Decoded response: {'result': [], 'resultType': 'success'}
PSC-IDE: No results found on Pursuit
```

Maybe it's probably related with the service not working properly?
- https://github.com/purescript/pursuit/issues/221

**Comment by FrigoEU** [comment]
This seems to work for me. I know there have been some problems with Pursuit in the recent past. Could you check if this is still relevant? 

Thanks!

**Comment by oblitum** [comment]
Looks fine now ;-)
