### ISSUE TITLE
Check for Neomake

### ISSUE THREAD

**Issue by leohahn** [FrigoEU/psc-ide-vim#2]
I tried working with neomake, but the syntax check does not work. I imagine it is not supported?
I prefer it because it is asyncronous (working with neovim).

**Comment by FrigoEU** [comment]
I use neovim as well and tried using neomake before, but I ran into some issues with neomake not correctly buffering stdout. That was some time ago though, so I'll take a look at this again soon.

**Comment by leohahn** [comment]
Cool, I saw that you can create Makers in neo-make, but I have no experience with vim-script. Anyway, cool library :+1:

**Comment by FrigoEU** [comment]
Finally did some work on this! I had some difficulties getting it to work, but I made a PR for Neomake with a PureScript/Pulp maker here: https://github.com/benekastah/neomake/pull/359. Getting it into the neomake master might take some time though, if it will happen at all. That said, I'm using it and it seems to work. You can install it with Plug or some other vim package manager:

Plug 'https://github.com/FrigoEU/neomake.git'

**Comment by leohahn** [comment]
Awesome :D, thanks for taking the time. I will give it a try.

**Comment by FrigoEU** [comment]
Output buffering still seems to be completely random, very frustrating. If you're really interested you can try, I'd like to hear what your experience is with it...

**Comment by FrigoEU** [comment]
Neomake is still giving me trouble, just can't seem to get the output from psc/pulp streamed correctly back into neovim... 

However I did add fast-rebuild support if you have psc >= 0.8.5.0, which is almost instant checking, so for me at least I don't feel the need to have Neomake anymore. Let me know what you think.

**Comment by leohahn** [comment]
Sorry for not answering before. I am currently not developing with Purescript (university classes and work).
But you can change it for sure if it is better. In the weekend I will have more time to play with the language.

**Comment by FrigoEU** [comment]
Closing for now.
