### ISSUE TITLE
Fails to start server

### ISSUE THREAD

**Issue by ChrisPenner** [FrigoEU/psc-ide-vim#22]
Hey there! I'm new to purescript and with strongly typed languages like this I feel blind writing code without a checker running on it, so thanks so much for putting this together!

I've got it installed (and the required dependencies), and I can actually use it just fine if I start up a `psc-ide-server` manually, but for some reason it seems to fail when trying to start the server itself, the port is definitely open, I can start my own server on that port without any trouble.

I switched the port using the option provided because the default one is taken on my machine, have any ideas why this isn't working out?

Here's the output when trying to check the type of a binding for `answer` inside my `src/Euler.purs` file.

Thanks again for pulling this together! Let me know if I can provide any info that might help!
(Also it might be helpful if it printed errors when it fails to connect rather than just saying 'No type info' 😄 )

```
PSCIDE s:getType currentModule: Euler
callPscIde: start: Executing command: {'currentModule': 'Euler', 'params': {'search': 'ans
wer', 'filters': []}, 'command': 'type'}
Your project is setup correctly.
callPscIde: No server found, looking for external server
callPscIde: Raw response of trying to reach external server: Couldn't connect to psc-ide-s
erver on port: PortNumber 3030 Error: connect: does not exist (Connection refused)^@
callPscIde: Decoded response of trying to reach external server: ''
callPscIde: No external server found, starting new server
PSCIDEstart: Starting psc-ide-server at /Users/chris/dev/purescript/hello
PSCIDEstart: Sleeping for 100ms so server can start up
callPscIde: Trying to reach server again
callPscIde: Raw response of trying to reach server again: Couldn't connect to psc-ide-serv
er on port: PortNumber 3030 Error: connect: does not exist (Connection refused)^@
callPscIde: Decoded response of trying to reach server again: ''
callPscIde: Server still can't be contacted, aborting...
PSC-IDE: No type information found for answer
```

**Comment by FrigoEU** [comment]
Hey Chris,

I tried to reproduce this but no luck so far, could you try running the start command just on the command line? It would be this:

```
psc-ide-server src/**/*.purs bower_components/**/*.purs -p 3030 -d /Users/chris/dev/purescript/hello
```

Hopefully this should show us what errors you're getting when running the server...

**Comment by ChrisPenner** [comment]
Hrmm, very strange, that command runs just fine, and it connects to the resulting server without any trouble too, but if I kill the server and let psc-ide-vim try and restart it it still fails 😢

**Comment by ChrisPenner** [comment]
I tried running 
system("psc-ide-server src/**/*.purs bower_components/**/*.purs -p 3030 -d /Users/chris/dev/purescript/hello > /dev/null &")

directly from in vim, and I think the issue may be related to the fact that I use zsh as my default shell:
`zsh:1: no matches found: src/**/*.purs`

**Comment by ChrisPenner** [comment]
For reference: https://github.com/FrigoEU/psc-ide-vim/blob/3c376289d368b7175cb6c10e2960f08830ee4cb4/ftplugin/purescript_pscide.vim#L70
Ah, looks like the commands being run assume that vim's current working directory is the project root (I use `set autochdir`, so my cwd is always the same as the file's path), not sure if that's being set anywhere, but if I ensure that vim's `pwd` is the project root then it works fine.

likely just be a matter of changing the relative routes [here](https://github.com/FrigoEU/psc-ide-vim/blob/3c376289d368b7175cb6c10e2960f08830ee4cb4/ftplugin/purescript_pscide.vim#L70) to be absolute by joining with the project dir `dir . "src/**/*.purs"`, etc.
or however you join paths in vim 😋 , something like this? I dunno:
`split(globpath(dir, '**'), '\n')`

**Comment by FrigoEU** [comment]
That makes perfect sense. `dir ."/src/**/*.purs"` etc works, tested it with `set autochdir`, that was indeed the problem. Thanks a lot for the investigation, don't think I would have found that by myself :).

I pushed this release just now (tag 0.6.1). If this works, could you let me know then I can close this issue.

**Comment by ChrisPenner** [comment]
Seems to have fixed it right up!
Thanks for maintaining this! And also for being so incredibly fast with a response and fix!
