### ISSUE TITLE
GoToDefinition error

### ISSUE THREAD

**Issue by ibrahimsag** [FrigoEU/psc-ide-vim#26]
I keep getting the following error while using the goto definition command. I couldn't figure out what might be the problem. can it be related to psc udpates?

```
:PSCIDEgoToDefinition
Multiple possibilities for Toggle
... i pick one ...
Error detected while processing function PSCIDEgoToDefinition[18]..<SNR>84_goToDefinition:
line    2:
E121: Undefined variable: name
E15: Invalid expression: (currentfile == a:definedAt.name)
Press ENTER or type command to continue
```

**Comment by andreasthoelke** [comment]
I seem to be getting the same error:
```
error detected while processing function PSCIDEgoToDefinition[10]..<SNR>138_goToDefinition:
E121: undefined variable: name 
E15 Invalid expression: (currentfile == a:definedAt.name)
```
In other situations `PSCIDEgoToDefinition` brings up a buffer with the correct file-path, but the buffer is empty.

I'm using MacVim 8.0.329

**Comment by FrigoEU** [comment]
This error should be gone now, not enough dynamic type checks!
