### ISSUE TITLE
Impossible to select from list of greater than length 10

### ISSUE THREAD

**Issue by jez** [FrigoEU/psc-ide-vim#27]
Sometimes `psc-ide-vim` has to ask the user to pick from a list of options. If that list of options has more than 10 things, it's impossible to select anything other than the first 10:

```viml
  "multiple possibilities
  if type(resp) == type({}) && resp.resultType ==# "success" && type(resp.result[0]) == type({})
    let choices = copy(resp.result)
    call map (choices, 'v:key. v:val["module"]')
    let choice = confirm("Multiple possibilities to import " . ident , join(choices, "\n"))
    if choice
      call s:importIdentifier(ident, resp.result[choice - 1].module)
    endif
    return
  endif
```

Look at the `call map ...` line. We're constructing our choices list by taking the element's index in the list (`v:key`) and concatenating it with the option's name (`v:val["module"]`).

Vim creates shortcuts based on the first character of the option. If there are less than 10 options, we're fine, because each option will start with a distinct number (i.e., 0 - 9).

However, at 10, we start to get 10Foo 11Bar 12Baz, all of which have the same first number.

I can't think of a quick and dirty way to fix this. Probably the only way would be to wrap around at 9 to letters of the alphabet, but that gets a bit hairy to implement.

**Comment by FrigoEU** [comment]
Hmm indeed. I actually stumbled upon this before, but it was never annoying enough for me to fix :). Seems not a big deal to change it to a for-loop, apart from Vim-script being awful. I'll see if I can implement this on a lazy morning. Thanks for the report!
