### ISSUE TITLE
Command not appearing on Vim command line

### ISSUE THREAD

**Issue by knaman2609** [FrigoEU/psc-ide-vim#30]
intstalled the plugin using vundle Plugin 'frigoeu/psc-ide-vim'. 

Dont even see the command appearing on vim command line 
:PSCIDEtype says Not an editor command: PSCIDEtype

**Comment by FrigoEU** [comment]
Do you get any errors in :messages?

**Comment by ravern** [comment]
You must be in a .purs file to use those commands.

**Comment by knaman2609** [comment]
sorry for the late reply

Somehow i didnt have this line in my vimrc. 
`filetype plugin indent on " required"` and the plugin wasnt working.. others plugins have no effect though.

I put it back and now everything is fine, thanks
