### ISSUE TITLE
use job-channel vim-8 feature

### ISSUE THREAD

**Issue by coot** [FrigoEU/psc-ide-vim#31]
The server could be run as a an async job and then all the commands would not block vim's interface.

**Comment by coot** [comment]
I started working on it. I have very primary version (does not support all commands yet), if anybody want to try [here is the code](https://github.com/coot/psc-ide-vim/tree/jobs) and report problems that would be helpful.

**Comment by coot** [comment]
@FrigoEU how old versions of vim do you want to support?

**Comment by chexxor** [comment]
Link to his progress: https://github.com/FrigoEU/psc-ide-vim/pull/34

**Comment by FrigoEU** [comment]
Million thanks to @coot for making this happen!
