### ISSUE TITLE
some way to look at formatted error under cursor

### ISSUE THREAD

**Issue by dlants** [FrigoEU/psc-ide-vim#39]
Long error messages (especially type errors) passed to syntastic become quite hard to read, since it seems that psc-ide-vim strips them of newlines during processing.

It would be great to have some easy way to look at the error under the cursor in a pretty-formatted way. Either by passing it to syntastic this way, or through a psc-ide-vim specific command.

Not sure how hard this is -- it seems that it may be a shortcoming of Syntastic/location lists https://github.com/vim-syntastic/syntastic/issues/1700

Thanks for the fantastic plugin!

**Comment by coot** [comment]
In the current version you can see formatted errors inside vim quick fix list. I tend to use
```
vert cope
```
I even have a simple command for that
```
com Vcopen vert cope|normal <C-W>=
```
Handy for very long error messages

**Comment by dlants** [comment]
Hey @coot thanks for the tip, but sorry if I'm not understanding correctly. Are you saying that when psc-ide-vim populates the quickfix list, you can display it pretty-printed? I haven't been able to get that to happen... from what I understand quickfix can only contain a single line per error, and strips out newline characters (there also seems to be a max line-length, so very long errors get cropped).

**Comment by coot** [comment]
Yes, that's true.  The common workaround for that is to put each line in a single entry and only put the filename and line number in the first one. vim will render it like this:
```
Test.Main |84 col 8 error| Could not match type
|| 
||     ( avar :: AVAR
||     , console :: CONSOLE
||     , dom :: DOM
||     , enzyme :: ENZYME
||     , st :: ST testRef0
||     | eff1
||     )
|| 
||   with type
|| 
||     ( console :: CONSOLE
||     , dom :: DOM
```

The `GhcMod` Haskell plugin is using this feature as well.
