### ISSUE TITLE
Ability to disable syntax checking  (or module loading) on buffer save and buffer load

### ISSUE THREAD

**Issue by paluh** [FrigoEU/psc-ide-vim#4]
Thanks for wonderful plugin!

As `pscid` has been released I've found that fastest workflow for me is to run `pscid -p 4242` in terminal, disable `sytnastic` and `psc-ide-vim` autocommands (I've done this by hand in plugin code).
Currently I'm using all helpful `PSCIDE*` calls for imports, types insertions/inspections etc. , but I'm reading compiler error messages and suggestions from `pscid` terminal.

Is it possible to disable syntax checking and module autoloading in more elegant way? Is there any way to configure such an behavior without plugin "monkey patching"?

**Comment by FrigoEU** [comment]
I've been working on a branch this morning that incorporates the fast rebuild into psc-ide-vim. It's insanely fast! I also incorporated a global variable, g:psc_ide_syntastic_mode:
0 = off
1 = use fast rebuild via psc-ide
2 = use full rebuild via pulp
Once I think it's stable I'll release this so you can choose what you want, even disable it. After using this though, I'm in love with using fast rebuild via syntastic, it's literally instant checking, so would definitely advise you to at least try it!

**Comment by paluh** [comment]
Wow! That's great! I will try it for sure! Thanks!

**Comment by FrigoEU** [comment]
Ok, done in 0.4.0. Let me know what you think! I did some sizeable changes to the plugin, so if something breaks I'll fix it asap.

**Comment by paluh** [comment]
Amazing! Now I don't need and want to use `0` any more :-) Again, thanks a lot for this wonderful plugin! I think that tooling with fast workflow is essential for Purescript adoption and success, which this language for sure deserves!

P.S. I think that you have forgotten to `git push --tags` ;-)
