### ISSUE TITLE
PSCIDEload fails.

### ISSUE THREAD

**Issue by pulltogether** [FrigoEU/psc-ide-vim#46]
```
:PSCIDEload
Your project is setup correctly.
callPscIde: Error: Failed to load
PSCIDEload: Failed to load. Error: ''
Press ENTER or type command to continue
```

**Comment by pulltogether** [comment]
We've also encountered `PSCIDEload: Failed to load. Error: '0'`

**Comment by coot** [comment]
Could you set `let psc_ide_log_level=3` and copy paste the output.

**Comment by gyulalaszlo** [comment]
You might be having the same issue as I had:

```
callPscIde: start: Executing command: {'command': 'load'}
callPscIde: Raw response: zsh:1: command not found: psc-ide-client^@
callPscIde: Decoded response: ''
callPscIde: Error: Failed to load
PSCIDEload: Failed to load. Error: '
```

It seems, that `psc-ide-client` is now `purs ide client` (as purescript does not install the command alias by default, only as a purs subcommand)

A quick and dirty hack (as I did not want to add a global alias) is to create a script somewhere in your PATH and run `purs ide ...` from there.

`~/.purs/bin/psc-ide-server`
```
#!/bin/zsh
purs ide server $@
```

`~/.purs/bin/psc-ide-client`
```
#!/bin/zsh
purs ide client $@
```

**Comment by FrigoEU** [comment]
Is this still an issue?

**Comment by coot** [comment]
Please reopen if you still have an issue with master branch.
