### ISSUE TITLE
`PSCIDEapplySUggestion` failes with `No suggestion found` ...

### ISSUE THREAD

**Issue by paluh** [FrigoEU/psc-ide-vim#47]
... but `g:psc_ide_suggestions` contains correct entry.

It seems that `g:psc_ide_suggestions` keys are based on relative paths, but `PSCIDEapplySuggestion` [builds absolute path value](https://github.com/FrigoEU/psc-ide-vim/blob/master/ftplugin/purescript_pscide.vim#L517) to make final lookup. When I drop `:p` modifier from `expand` call everything works as expected.

I can provide appropriate pull request but I'm not sure if this behavior is somehow related to my configuration and it's only me who is experiencing this problem.

**Comment by kritzcreek** [comment]
@paluh I think this will be fixed with the next release. See https://github.com/purescript/purescript/pull/2867

**Comment by paluh** [comment]
@kRITZCREEK Thanks for clarification... and for your wonderful Work on Purescript!

I'm closing it for now.
