### ISSUE TITLE
Line above cursor gets deleted on :PSCIDEimportIdentifier

### ISSUE THREAD

**Issue by andreasthoelke** [FrigoEU/psc-ide-vim#49]
After I updated to what's currently on master, I noticed that the line above the cursor gets deleted when I run :PSCIDEimportIdentifier and a new `import ..` line get's added at the top.

I didn't see this problem in earlier versions, however back then I saw my vim-folds shift when a new import line was added.

**Comment by johnmendonca** [comment]
I am seeing this issue as well. The number of lines above the cursor stays constant.  When an import line is added, the line above cursor is removed.

**Comment by paluh** [comment]
It seems that there was an `append(nrOfOldlinesUnderLine, linesToAppend)` call in this `if` branch somewhere in the past:

https://github.com/FrigoEU/psc-ide-vim/blob/5aa51d49b59ce9d3916796a7a5a940f17eee4b0c/ftplugin/purescript_pscide.vim#L262

but now it is missing:

https://github.com/FrigoEU/psc-ide-vim/blob/master/ftplugin/purescript_pscide.vim#L260

Am I right?

I wonder if we should bring back cursor position setup (which was there before) somewhere near too.

**Comment by paluh** [comment]
It seems that my [two minor changes](https://github.com/FrigoEU/psc-ide-vim/compare/master...paluh:master) fix these issues (cursor position and deleted line). I've got also "temprorary workaround" for `PSCIDEapplySuggestion` (as it is really `purs ide` bug), but I'm not sure if I should include it in pull request. @FrigoEU what do you think?

**Comment by andreasthoelke** [comment]
Thanks @paluh, your changes fix the issue for me!

**Comment by FrigoEU** [comment]
Could you check if this is still a problem on the new release?

**Comment by johnmendonca** [comment]
This is fixed for me on the latest release, thanks!
