### ISSUE TITLE
PSCIDEcaseSplit - either documentation or implementation is incorrect

### ISSUE THREAD

**Issue by LightAndLight** [FrigoEU/psc-ide-vim#59]
The gif in the docs shows :PSCIDEcaseSplit should prompting the user to enter a type, but the current build requires that the user pass the type as an argument to the ex command.

So either the gif and suggested key mapping should be updated, or the command should be changed to behave as in the docs. I'll submit a PR that does the latter.

**Comment by coot** [comment]
https://github.com/prabirshrestha/async.vim/issues/8
