### ISSUE TITLE
rename async#job#start to something else

### ISSUE THREAD

**Issue by prabirshrestha** [FrigoEU/psc-ide-vim#61]
https://github.com/FrigoEU/psc-ide-vim/pull/51 adds async.vim support.

@FrigoEU @coot I would suggest changing the public api names to `pscidevim#jobs#start()` or something down that line so it doesn't conflict with the actual async.vim. More info at https://github.com/k-takata/minpac/issues/3#issuecomment-288865471

```
" public apis {{{
function! async#job#start(cmd, opts) abort
    return s:job_start(a:cmd, a:opts)
endfunction

function! async#job#stop(jobid) abort
    call s:job_stop(a:jobid)
endfunction

function! async#job#send(jobid, data) abort
    return s:job_send(a:jobid, a:data)
endfunction
" }}}
```

**Comment by coot** [comment]
vim8 has packages if neovim has a similar feature we could use that to the avoid namespace issues.

**Comment by coot** [comment]
I checked that packages work both in vim an nvim.  You can move `autostart/async/job.vim` to `~/.vim/pack/async/start/async/autostart/async/job.vim` and use [async-package branch](https://github.com/coot/psc-ide-vim/tree/async-package).
