### ISSUE TITLE
Update breaks Neovim

### ISSUE THREAD

**Issue by arthurxavierx** [FrigoEU/psc-ide-vim#62]
The latest update which enables the use of async jobs seems to break the usage of this plugin with Neovim. When running `:PSCIDEload` with logging enabled on level 3 I get the following errors:

```
Error detected while processing function PSCIDEload:
line   13:
E15: Invalid expression: > s:PSCIDEloadCallback(a:logLevel, resp)} )
E116: Invalid arguments for function <SNR>87_callPscIde
```

Is this expected behavior?

**Comment by FrigoEU** [comment]
It's not mentioned in the documentation (yet), but you need Neovim 0.2 or higher. Could you check which version you're using? I'm using it with the last official Neovim release (0.2.0) and it works for me.

**Comment by arthurxavierx** [comment]
That was it. I was using v0.1.5-dev. Just upgraded and it works perfectly! Thanks for the help @FrigoEU! :)
