### ISSUE TITLE
ALE syntax checking

### ISSUE THREAD

**Issue by skeate** [FrigoEU/psc-ide-vim#69]
Is there any chance of getting this to work with [ALE](https://github.com/w0rp/ale)?

**Comment by coot** [comment]
I'd prefer to have it in a separate plugin. I think we expose enough to to build integration for it, but I've never used ALE.

**Comment by coot** [comment]
@FrigoEU please reopen if you don't agree :)

**Comment by sriharshachilakapati** [comment]
I think ALE is better than Syntastic, because it doesn't slow down VIM when opening files in large projects, and also it allows for on the fly error checking.

**Comment by jdwolk** [comment]
Agreed. I've tried ALE and I love it. It would be awesome if I could make the switch to ALE but Purescript / psc-ide-vim keep me holding onto Syntastic a bit longer
