### ISSUE TITLE
psc-ide-vim is giving error detected while processing

### ISSUE THREAD

**Issue by stifspear** [FrigoEU/psc-ide-vim#71]
```
Error detected while processing function PSCIDEtype:
line    1:
E15: Invalid expression: > s:PSCIDEtypeCallback(a:ident, resp.result, a:filterModules) } )
E116: Invalid arguments for function <SNR>45_getType

Error detected while processing function <SNR>30_BufWritePostHook[4]..<SNR>30_UpdateErrors[15]..<SNR>30_CacheErrors[39]..18[1]..17[24]..SyntaxCheckers_purescript_pscide_GetLocList:
line    4:
E15: Invalid expression: > s:rebuildOutputToSyntastic(PSCIDErebuild(0))} })
E116: Invalid arguments for function SyntasticMake({ 'makeprg': self.makeprgBuild({'exe': 'echo', 'args': 'a'}),  'errorformat': '%t:%f:%l:%c:%m', 'Preprocess': {args -> s:rebuildOutputToSyntast
ic(PSCIDErebuild(0))} })
E15: Invalid expression: SyntasticMake({ 'makeprg': self.makeprgBuild({'exe': 'echo', 'args': 'a'}),  'errorformat': '%t:%f:%l:%c:%m', 'Preprocess': {args -> s:rebuildOutputToSyntastic(PSCIDEreb
uild(0))} })
Error detected while processing function <SNR>30_BufWritePostHook[4]..<SNR>30_UpdateErrors[15]..<SNR>30_CacheErrors:
line   39:
E170: Missing :endfor
Error detected while processing function <SNR>30_BufWritePostHook[4]..<SNR>30_UpdateErrors:
line   15:
E171: Missing :endif
```

Purescript is installed 
Purescript-vim is also installed
But I am getting some error with psc-ide-vim.
I dont know the reason why.
Reporting issue for the first time so please ignore any mistakes

**Comment by coot** [comment]
Thanks for the bug report.  I am not using syntastic myself (you can disable it with `let g:psc_ide_syntastic_mode = 0` in your `vimrc` file).

I can reproduce it.

**Comment by coot** [comment]
Please check the master branch, and reopen if it still breaks for you.

**Comment by stifspear** [comment]
Thank you for your reply. These errors are generated when I am saving my file. 

"src/Main.purs" 9L, 198C written
Error detected while processing function PSCIDErebuild:
line    5:
E121: Undefined variable: v:t_func
E15: Invalid expression: a:0 >= 1 && type(a:1) == v:t_func
line   21:
E15: Invalid expression: > CallBack(s:PSCIDErebuildCallback(filename, msg, silent)) } )
E116: Invalid arguments for function purescript#ide#call

**Comment by coot** [comment]
What version of vim are you using? We are currently supporting vim-8 and some recent version of neovim.

**Comment by stifspear** [comment]
vim 7.4 
I will report after updating to vim 8.0

**Comment by stifspear** [comment]
Yes it is working for vim 8.0. But when I am putting  g:psc_ide_syntastic_mode = 0 in my .vimrc Main.purs opens fine but it does not give me error reports for my Main.purs file. But when I remove "g:psc_ide_syntastic_mode = 0" line it gives this error
Error detected while processing function <SNR>43_autoStart:
line    1:
E121: Undefined variable: g:psc_ide_syntastic_mode
E15: Invalid expression: g:psc_ide_syntastic_mode == 0

but after I press enter and open file it shows me errors on my Main.purs program. I hope you understand what I just wrote.
Thank You

**Comment by coot** [comment]
with `psc_ide_syntastic_mode=0` `psc-ide-vim` runs `PSCIDErebuild` on writes, it does not run it on `BufRead` autocommand.  Maybe I should change it...
