### ISSUE TITLE
"Go to definition", et al., unaware of imported names

### ISSUE THREAD

**Issue by maackle** [FrigoEU/psc-ide-vim#81]
When using `:PSCIDEgoToDefinition`, I get too many suggestions. For instance, if `div` is the token under the cursor, 

```
Multiple possibilities for div
[0] App.Repl, (1) CSS, (2) CSS.Elements, (3) Data.EuclideanRing, (4) Data.Field, (5) Optic.Core, (6) Optic.Setter, (7) Prelude, (8) React.DOM, (9) React.DOM.Dynamic, (A) Text.Smolder.HTML:
```

Even though I have `import Text.Smolder.HTML (div)` in my import declarations.

I even get a warning when trying to `import Prelude` about shadowing `div` (from Prelude), so the ide server is clearly aware of the imports in some capacity. Is there any way to filter out the suggestions with the knowledge of the imports?

Seems to be a similar problem for getting type annotations.

**Comment by coot** [comment]
Thanks for the report. I am currently working on qualified identifiers.   Just pushed changes that should fix your case too. Note that I change command names in the master branch.  There's also vim documentation so you can check it there what are the new names.

Now you can
```
Pgoto React.DOM.div
```
and you will land in `React.DOM` module (assuming that you imported `React.DOM` with `React.DOM` qualified (it will work with any qualifier you picked, it just has to agree with the import section).

**Comment by maackle** [comment]
Your changes certainly did fix my case, and it put a huge smile on my face to wake up the morning after my issue to find it resolved! Thank you!
