### ISSUE TITLE
`PSCIDEremoveImportQualifications` is referenced but does not exist

### ISSUE THREAD

**Issue by maackle** [FrigoEU/psc-ide-vim#88]
via `:PremoveImportQualifications`

**Comment by coot** [comment]
Thanks!

**Comment by maackle** [comment]
What did that function do, anyway? And is there an alternative for it?

**Comment by coot** [comment]
It was removing qualifiers:
```
%:s/^\(import\s*[[:alpha:].]\s\+([^)]*\).*/\1
```
I just thought it's not something that the plugin should provide.  It's too specific and to simple to just define in by someone in his .vim config.

**Comment by coot** [comment]
Anyway, with `Pimport`, `Papply!` and its integration with omni- and user- completion functions, there's no need to touch the imports almost at all.
