### ISSUE TITLE
How to debug syntastic checker?

### ISSUE THREAD

**Issue by alexmingoia** [FrigoEU/psc-ide-vim#9]
I'm having trouble getting the syntastic checker to work on a fresh install.

Syntastic does not list any available checkers for purescript. I have a fresh vim install, latest version of syntastic, purescript-vim, and psc-ide-vim installed using vundle. If I echo the `$PATH` in vim I get the correct path, and `psc`, `psc-ide-server`, etc. is available.

Also, I can run commands like `:PSCIDEtype` just fine. It appears its just the syntastic integration. Running with `g:syntastic_debug = 3` results in:

```
"src/App.purs" 56L, 1567C
syntastic: 0.095408: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote
= '', &shellxescape = ''
syntastic: 0.095797: UpdateErrors (auto): default checkers
syntastic: 0.096078: CacheErrors: default checkers
syntastic: 0.096597: g:syntastic_aggregate_errors = 0
syntastic: 0.096771: getcwd() = '/Users/alex/Projects/orpheus'
syntastic: 0.212382: CacheErrors: Checker purescript/pscide is not available
syntastic: 0.212670: CacheErrors: no checkers available for purescript
syntastic: 0.212767: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}
```

`:SyntasticInfo`:

```
Syntastic version: 3.7.0-137 (Vim 704, Darwin)
Info for filetype: purescript
Global mode: active
Filetype purescript is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
```

Any ideas on how I should debug this further?

**Comment by alexmingoia** [comment]
It turns out it was because even though `psc-ide-server` and `psc-ide-client` binaries were installed, my `psc` was `0.8.3` and needed to be `0.8.4+`.

**Comment by kritzcreek** [comment]
@alexmingoia I suggest you update to 0.8.5 as that will give you the super fast rebuilding! Check the syntastic section in the README. Also you don't need to install the psc-ide binaries "extra" they are shipped with the compiler.
